spring:
  application:
    name: budong-budong

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  elasticsearch:
    uris: ${ELASTIC_SEARCH:http://localhost:9200}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  toss:
    api:
      confirm-url: https://api.tosspayments.com/v1/payments/confirm
    secret-key: ${TOSS_SECRET_KEY}

external:
  api:
    service-key: ${API_SERVICE_KEY}

naver:
  map:
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}

kakao:
  map:
    rest-api-key: ${KAKAO_MAP_REST_API_KEY}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  from-number: ${COOLSMS_FROM_NUMBER}

storage:
  type: ${STORAGE_TYPE:local}
  presign-expire-minutes: ${STORAGE_PRESIGN_EXPIRE_MINUTES:10}

file:
  upload-dir: uploads
  base-url: http://localhost:8080/uploads

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
    s3:
      bucket: ${AWS_S3_BUCKET:}
    region:
      static: ${AWS_REGION:ap-northeast-2}

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE
    org.springframework.data.elasticsearch: DEBUG
    tracer: TRACE
  slack:
    webhook: ${SLACK_WEBHOOK_URL}